FROM mysql:5
FROM python:3

RUN pip install --upgrade pip && \
    # pip install --no-cache-dir sys && \
    pip install --no-cache-dir numpy && \
    pip install --no-cache-dir pymysql

COPY ./install.sh /install_scripts/install.sh
RUN sh /install_scripts/install.sh && rm -rf /install_scripts

ENV MYSQL_ROOT_PASSWORD=password
ENV TZ=America/New_York

COPY ./iot_schema.sql ./package.json ./REST.js ./Server.js ./utils.js ./start.sh ./test_make_orders.js /iot-server/
COPY ./users.csv /var/lib/mysql-files/
EXPOSE 3000
EXPOSE 3306
WORKDIR /iot-server
RUN ["chmod", "+x", "start.sh"]
CMD ./start.sh

# docker run -it --name iot -p 3000:3000 -p 3306:3306 iot-server
